# Packs every mp3 in .\sfx into sfx\sfx.data.js as base64, so the game can play its recorded audio when the HTML is opened
# straight from disk (file:// blocks fetch). Run after adding or regenerating clips:  powershell -ExecutionPolicy Bypass -File .\build-sfx-data.ps1
$root=Split-Path -Parent $MyInvocation.MyCommand.Path
$dir=Join-Path $root 'sfx'
$sb=New-Object System.Text.StringBuilder
[void]$sb.Append("// Generated by build-sfx-data.ps1: base64 copies of sfx/*.mp3 for direct file:// play.`nwindow.BeltRunnerSfxData={")
$first=$true
foreach ($f in Get-ChildItem $dir -Filter *.mp3 | Sort-Object Name){
  if (-not $first){ [void]$sb.Append(',') }; $first=$false
  $name=[IO.Path]::GetFileNameWithoutExtension($f.Name)
  [void]$sb.Append('"'+$name+'":"'+[Convert]::ToBase64String([IO.File]::ReadAllBytes($f.FullName))+'"')
}
[void]$sb.Append("};`n")
[IO.File]::WriteAllText((Join-Path $dir 'sfx.data.js'), $sb.ToString())
"wrote sfx\sfx.data.js  $((Get-Item (Join-Path $dir 'sfx.data.js')).Length) bytes"
